namespace TallyConnector.Models.TallyPrime.V5.Masters;

[XmlType(AnonymousType = true)]
[XmlRoot("LEDGER")]
[GenerateITallyRequestableObect]
[GenerateMeta]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class Ledger :V4.Masters.Ledger
{
}
